apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.configMap.annotations | nindent 4 }}
data:
  polaris.yaml: |
    global:
      serverConnector:
        addresses:
          {{- range .Values.polaris.config.global.serverConnector.addresses }}
          - {{ . }}
          {{- end }}
